### PR TITLE
moved API key to .env file

### PR DESCRIPTION
**Pull request by lilywright17**
rather than in code! I made a new .env file in the front end, not sure if this was necessary but it didn't seem to like it when I tried to use the one in the backend
Deactivated the API shared previously to prevent it being used elsewhere!

### CODE REVIEW

**Comment by th4lesvic** [comment]
Hi @lilywright17 , this morning [Kenny suggested](https://summercfgdegree2024.slack.com/archives/C072VK5T19B/p1723624969257639?thread_ts=1723624954.222689&cid=C072VK5T19B) that it's better practice to connect third-party APIs in the backend. 

When I was working with Cloudinary, I initially set it up in the frontend, but it caused bugs everywhere, so I had to move the configuration to the backend. I think there is a way to co-exist within credentials for different APIs

The env.EXAMPLE in the BE should look like this... in the recent version. But yours is different. Maybe that could be the reason for one of the conflicts?
image

**Review by th4lesvic — CHANGES_REQUESTED** [review]
Hi @lilywright17 , this morning [Kenny suggested](https://summercfgdegree2024.slack.com/archives/C072VK5T19B/p1723624969257639?thread_ts=1723624954.222689&cid=C072VK5T19B) that it's better practice to connect third-party APIs in the backend. 

`/backend -> env.EXAMPLE ` seems not up to latest version (attached a snapshot of how the .env.EXAMPLE file could be) 
 
Please consider if there is a way to move the Google API credentials/config to the BE. 

image

**Comment by Katie-W-22** [comment]
Lily, after chatting with Vic, I think we'll close your PR #72, can you then please go onto dev branch and 'git pull origin dev', then go back onto your map branch, git merge dev, see if everything is ok with your map, and then do a new PR?

**Comment by Katie-W-22** [comment]
Closed...please see message on Slack re pull on dev :-)

**Pull request closed without merging**
